using System;

public static partial class BanterContenidoLocal
{
    static partial void RegistrarContenido()
    {
        RegistrarBloque<ClaseCaballero>(ContenidoCaballero);
        RegistrarBloque<ClaseExplorador>(ContenidoExplorador);
        RegistrarBloque<ClasePurificadora>(ContenidoPurificadora);
        RegistrarBloque<ClaseAcechador>(ContenidoAcechador);
        RegistrarBloque<ClaseCanalizador>(ContenidoCanalizador);
        RegistrarBloque<ClaseDuelista>(ContenidoDuelista);
    }

    private static void RegistrarBloque<TUnidad>(string contenido)
        where TUnidad : Unidad
    {
        string[] filas = contenido.Split(
            new[] { '\r', '\n' },
            StringSplitOptions.RemoveEmptyEntries);

        foreach (string filaCruda in filas)
        {
            string fila = filaCruda.Trim();
            if (fila.Length == 0)
            {
                continue;
            }

            string[] campos = fila.Split('|');
            if (campos.Length != 5 ||
                !Enum.TryParse(campos[1], out BanterDisparador disparador))
            {
                throw new InvalidOperationException(
                    $"Contenido de banter inválido: {fila}");
            }

            Registrar<TUnidad>(new BanterLineaLocal(
                campos[0],
                disparador,
                campos[2],
                campos[3],
                campos[4]));
        }
    }

    private const string ContenidoCaballero = @"
cab_inicio_01|ComenzarBatalla|¡Formen filas! Hoy lucharemos con honor.|Form ranks! Today we fight with honor.|Formem fileiras! Hoje lutaremos com honra.
cab_inicio_02|ComenzarBatalla|Acero en mano. Que comience la batalla.|Steel in hand. Let the battle begin.|Aço em punho. Que comece a batalha.
cab_idle_01|IdleTurno|¿Qué esperamos? ¡Al ataque!|What are we waiting for? Attack!|O que estamos esperando? Ao ataque!
cab_idle_02|IdleTurno|Mi espada se oxida...|My sword is gathering rust...|Minha espada está enferrujando...
cab_mata_01|EnemigoDerrotado|¡Buen golpe!|Good strike!|Belo golpe!
cab_mata_02|EnemigoDerrotado|Así se combate. Un honor luchar a tu lado.|That's how you fight. An honor to stand by your side.|É assim que se luta. Uma honra lutar ao seu lado.
cab_muere_01|AliadoDerrotado|¡No! Su sacrificio será vengado...|No! Their sacrifice will be avenged...|Não! Seu sacrifício será vingado...
cab_muere_02|AliadoDerrotado|Cayó con honor…|They fell with honor…|Tombou com honra…
cab_refuerzo_01|RefuerzoEnemigo|¡Más enemigos! Más gloria...|More enemies! More glory...|Mais inimigos! Mais glória...
cab_refuerzo_02|RefuerzoEnemigo|Mi brazo aún tiene fuerza.|My arm still has strength.|Meu braço ainda tem força.
cab_crit_rec_01|CriticoRecibido|Argh... ¡Buen golpe!|Argh... Good strike!|Argh... Belo golpe!
cab_crit_rec_02|CriticoRecibido|La sangre no quiebra mi juramento.|Blood cannot break my oath.|Sangue nenhum quebra meu juramento.
cab_crit_hecho_01|CriticoRealizado|¡Muere!|Die!|Morra!
cab_crit_hecho_02|CriticoRealizado|¡Que prueben nuestro acero!|Let them taste our steel!|Que provem do nosso aço!
cab_moral_mas_01|MoralAumentaEtapa|Unidos venceremos...|United, we shall prevail...|Unidos, venceremos...
cab_moral_mas_02|MoralAumentaEtapa|Sus huestes flaquean.|Their ranks are faltering.|As fileiras deles estão vacilando.
cab_moral_menos_01|MoralDisminuyeEtapa|¡No cedan! El miedo deshonra a los vivos.|Do not yield! Fear dishonors the living.|Não cedam! O medo desonra os vivos.
cab_moral_menos_02|MoralDisminuyeEtapa|No bajen la cabeza o la perderán...|Keep your heads up, or you will lose them...|Não baixem a cabeça, ou vão perdê-la...
cab_apoyo_01|HabilidadAliadaRecibida|Gracias… lo haré valer...|Thank you… I will make it count...|Obrigado… farei valer a pena...
cab_apoyo_02|HabilidadAliadaRecibida|Buen apoyo.|Good support.|Bom apoio.
cab_vida_critica_01|VidaCritica|Aún sigo en pie.|I am still standing.|Ainda estou de pé.
cab_vida_critica_02|VidaCritica|No caeré mientras pueda sostener el acero.|I will not fall while I can still hold steel.|Não cairei enquanto puder empunhar o aço.
cab_pifia_01|Pifia|¡Vuelve a intentarlo!|Try again!|Tente de novo!
cab_pifia_02|Pifia|Concéntrate.|Focus.|Concentre-se.
";

    private const string ContenidoExplorador = @"
exp_inicio_01|ComenzarBatalla|No me gusta este lugar...|I don't like this place...|Não gosto deste lugar...
exp_inicio_02|ComenzarBatalla|Procuremos seguir respirando.|Let's try to keep breathing.|Vamos tentar continuar respirando.
exp_idle_01|IdleTurno|Deberíamos apresurarnos...|We should hurry...|Deveríamos nos apressar...
exp_idle_02|IdleTurno|Tómatelo con calma…|Take your time…|Sem pressa…
exp_mata_01|EnemigoDerrotado|Bien hecho.|Well done.|Muito bem.
exp_mata_02|EnemigoDerrotado|Eso fue... eficaz.|That was... effective.|Isso foi... eficaz.
exp_muere_01|AliadoDerrotado|No... no tenía que terminar así.|No... it wasn't supposed to end like this.|Não... não devia ter acabado assim.
exp_muere_02|AliadoDerrotado|Maldición…|Damn it…|Maldição…
exp_refuerzo_01|RefuerzoEnemigo|Claro. Porque no había suficientes.|Of course. Because there weren't enough already.|Claro. Porque já não eram suficientes.
exp_refuerzo_02|RefuerzoEnemigo|Refuerzos... ¡atentos!|Reinforcements... stay sharp!|Reforços... atenção!
exp_crit_rec_01|CriticoRecibido|¡Eso dolió!|That hurt!|Isso doeu!
exp_crit_rec_02|CriticoRecibido|Eso estuvo demasiado cerca...|That was far too close...|Essa passou perto demais...
exp_crit_hecho_01|CriticoRealizado|Entre ceja y ceja...|Right between the eyes...|Bem entre os olhos...
exp_crit_hecho_02|CriticoRealizado|¡Justo al corazón!|Right through the heart!|Bem no coração!
exp_moral_mas_01|MoralAumentaEtapa|Bien... quizá salgamos de esta.|Good... maybe we'll make it out of this.|Ótimo... talvez a gente saia dessa.
exp_moral_mas_02|MoralAumentaEtapa|Eso mejora nuestras probabilidades.|That improves our odds.|Isso melhora nossas chances.
exp_moral_menos_01|MoralDisminuyeEtapa|Esto empieza a verse mal.|This is starting to look bad.|Isso está começando a ficar feio.
exp_moral_menos_02|MoralDisminuyeEtapa|No quiero morir…|I don't want to die…|Eu não quero morrer…
exp_apoyo_01|HabilidadAliadaRecibida|Eso ayuda.|That helps.|Isso ajuda.
exp_apoyo_02|HabilidadAliadaRecibida|Gracias.|Thanks.|Obrigado.
exp_vida_critica_01|VidaCritica|Esto se está poniendo feo...|This is getting ugly...|Isso está ficando feio...
exp_vida_critica_02|VidaCritica|Necesito salir de aquí... pronto.|I need to get out of here... soon.|Preciso sair daqui... logo.
exp_pifia_01|Pifia|Y mi vida depende de ti...|And my life depends on you...|E a minha vida depende de você...
exp_pifia_02|Pifia|Puede pasar…|It happens…|Acontece…
";

    private const string ContenidoPurificadora = @"
pur_inicio_01|ComenzarBatalla|La luz camina con nosotros.|The light walks with us.|A luz caminha conosco.
pur_inicio_02|ComenzarBatalla|¡Serán purificados!|You will be purified!|Vocês serão purificados!
pur_idle_01|IdleTurno|La prudencia es virtud...|Prudence is a virtue...|A prudência é uma virtude...
pur_idle_02|IdleTurno|Analiza a los impuros...|Study the impure...|Analise os impuros...
pur_mata_01|EnemigoDerrotado|La luz guio tu mano.|The light guided your hand.|A luz guiou sua mão.
pur_mata_02|EnemigoDerrotado|Un impuro menos…|One less impure soul…|Um impuro a menos…
pur_muere_01|AliadoDerrotado|Que la luz reciba su alma.|May the light receive their soul.|Que a luz receba sua alma.
pur_muere_02|AliadoDerrotado|Tu memoria será mi plegaria…|Your memory will be my prayer…|Sua memória será minha prece…
pur_refuerzo_01|RefuerzoEnemigo|Más impuros para purificar.|More impure souls to cleanse.|Mais impuros para purificar.
pur_refuerzo_02|RefuerzoEnemigo|Que vengan. La luz no retrocede.|Let them come. The light does not retreat.|Que venham. A luz não recua.
pur_crit_rec_01|CriticoRecibido|¡Mi fe me sanará!|My faith will heal me!|Minha fé me curará!
pur_crit_rec_02|CriticoRecibido|La luz no sangrará…|The light will not bleed…|A luz não sangrará…
pur_crit_hecho_01|CriticoRealizado|¡Purificado!|Purified!|Purificado!
pur_crit_hecho_02|CriticoRealizado|La luz ha dictado sentencia.|The light has passed judgment.|A luz proferiu a sentença.
pur_moral_mas_01|MoralAumentaEtapa|La esperanza aumenta...|Hope is rising...|A esperança cresce...
pur_moral_mas_02|MoralAumentaEtapa|¡Que arda nuestra llama!|Let our flame blaze!|Que nossa chama arda!
pur_moral_menos_01|MoralDisminuyeEtapa|La fe tambalea… resistid…|Faith wavers… stand firm…|A fé vacila… resistam…
pur_moral_menos_02|MoralDisminuyeEtapa|La oscuridad crece…|The darkness grows…|A escuridão cresce…
pur_apoyo_01|HabilidadAliadaRecibida|Eres muy amable...|You are very kind...|Você é muito gentil...
pur_apoyo_02|HabilidadAliadaRecibida|Te devolveré el favor…|I will return the favor…|Retribuirei o favor…
pur_vida_critica_01|VidaCritica|La luz aún no me abandona.|The light has not abandoned me yet.|A luz ainda não me abandonou.
pur_vida_critica_02|VidaCritica|Mi fe resistirá este dolor.|My faith will endure this pain.|Minha fé resistirá a esta dor.
pur_pifia_01|Pifia|Déjate guiar por la luz...|Let the light guide you...|Deixe a luz guiar você...
pur_pifia_02|Pifia|¡Recupérate! Tú puedes.|Recover! You can do this.|Recupere-se! Você consegue.
";

    private const string ContenidoAcechador = @"
ace_inicio_01|ComenzarBatalla|Yo pido a ese...|That one is mine...|Aquele é meu...
ace_inicio_02|ComenzarBatalla|Ni sabrán qué les pasó…|They won't even know what hit them…|Nem vão saber o que os atingiu…
ace_idle_01|IdleTurno|¡Apresúrate!|Hurry up!|Apresse-se!
ace_idle_02|IdleTurno|Zzz…|Zzz…|Zzz…
ace_mata_01|EnemigoDerrotado|Un golpe limpio...|A clean strike...|Um golpe limpo...
ace_mata_02|EnemigoDerrotado|¡Ese era mío!|That one was mine!|Aquele era meu!
ace_muere_01|AliadoDerrotado|Lamentable...|Pathetic...|Lamentável...
ace_muere_02|AliadoDerrotado|Todo depende de mí...|Everything depends on me now...|Agora tudo depende de mim...
ace_refuerzo_01|RefuerzoEnemigo|¡Más sangre para desparramar!|More blood to spill!|Mais sangue para derramar!
ace_refuerzo_02|RefuerzoEnemigo|No se acaban jamás...|They never stop coming...|Eles nunca acabam...
ace_crit_rec_01|CriticoRecibido|Argh... ya verás...|Argh... you'll see...|Argh... você vai ver...
ace_crit_rec_02|CriticoRecibido|Hmpf... Ya me tocará...|Hmph... My turn will come...|Hmpf... Minha vez vai chegar...
ace_crit_hecho_01|CriticoRealizado|¡Sufre!|Suffer!|Sofra!
ace_crit_hecho_02|CriticoRealizado|Así termina toda resistencia.|This is how all resistance ends.|É assim que toda resistência termina.
ace_moral_mas_01|MoralAumentaEtapa|Esto pinta bien...|This is looking good...|Isso está ficando bom...
ace_moral_mas_02|MoralAumentaEtapa|*Risa* los mataremos…|*Laughs* We'll kill them all…|*Risada* Vamos matar todos eles…
ace_moral_menos_01|MoralDisminuyeEtapa|Este grupo es débil...|This group is weak...|Este grupo é fraco...
ace_moral_menos_02|MoralDisminuyeEtapa|Quizás deba escabullirme…|Perhaps I should slip away…|Talvez eu deva escapar…
ace_apoyo_01|HabilidadAliadaRecibida|Nadie te pidió ayuda… pero gracias...|No one asked for your help… but thanks...|Ninguém pediu sua ajuda… mas obrigado...
ace_apoyo_02|HabilidadAliadaRecibida|Bien. Ahora apártate y observa.|Good. Now step aside and watch.|Muito bem. Agora saia da frente e observe.
ace_vida_critica_01|VidaCritica|Todavía no han terminado conmigo.|They are not done with me yet.|Ainda não acabaram comigo.
ace_vida_critica_02|VidaCritica|Van a pagar por esto.|They will pay for this.|Eles vão pagar por isso.
ace_pifia_01|Pifia|Patético...|Pathetic...|Patético...
ace_pifia_02|Pifia|Débil…|Weak…|Fraco…
";

    private const string ContenidoCanalizador = @"
can_inicio_01|ComenzarBatalla|Es hora de descargar mi poder...|Time to unleash my power...|É hora de liberar meu poder...
can_inicio_02|ComenzarBatalla|¡Todos serán desintegrados!|You will all be disintegrated!|Todos vocês serão desintegrados!
can_idle_01|IdleTurno|El tiempo pasa...|Time passes...|O tempo passa...
can_idle_02|IdleTurno|Mi poder se impacienta...|My power grows impatient...|Meu poder está ficando impaciente...
can_mata_01|EnemigoDerrotado|Buen trabajo…|Good work…|Bom trabalho…
can_mata_02|EnemigoDerrotado|Sigue así...|Keep it up...|Continue assim...
can_muere_01|AliadoDerrotado|No… amigo...|No… my friend...|Não… meu amigo...
can_muere_02|AliadoDerrotado|No pude preverlo…|I failed to foresee this…|Não consegui prever isso…
can_refuerzo_01|RefuerzoEnemigo|Mi energía aún no se acaba...|My energy is far from spent...|Minha energia ainda não se esgotou...
can_refuerzo_02|RefuerzoEnemigo|¡Que sigan llegando!|Let them keep coming!|Que continuem vindo!
can_crit_rec_01|CriticoRecibido|Argh... mi energía flaquea...|Argh... my energy falters...|Argh... minha energia vacila...
can_crit_rec_02|CriticoRecibido|Argh... ya verás...|Argh... you'll see...|Argh... você vai ver...
can_crit_hecho_01|CriticoRealizado|De diez… o de 20 en realidad...|A ten… or a twenty, actually...|Dez… ou vinte, na verdade...
can_crit_hecho_02|CriticoRealizado|¡Sí!|Yes!|Sim!
can_moral_mas_01|MoralAumentaEtapa|Todo se va alineando...|Everything is aligning...|Tudo está se alinhando...
can_moral_mas_02|MoralAumentaEtapa|¡Nuestra energía brilla!|Our energy shines!|Nossa energia brilha!
can_moral_menos_01|MoralDisminuyeEtapa|Nuestro poder flaquea...|Our power is faltering...|Nosso poder está vacilando...
can_moral_menos_02|MoralDisminuyeEtapa|Controlen sus emociones…|Control your emotions…|Controlem suas emoções…
can_apoyo_01|HabilidadAliadaRecibida|Gracias por tu colaboración...|Thank you for your assistance...|Obrigado pela colaboração...
can_apoyo_02|HabilidadAliadaRecibida|Interesante...|Interesting...|Interessante...
can_vida_critica_01|VidaCritica|Mi cuerpo flaquea... mi poder no.|My body falters... my power does not.|Meu corpo vacila... meu poder não.
can_vida_critica_02|VidaCritica|Debo terminar esto pronto.|I must end this soon.|Preciso acabar com isso logo.
can_pifia_01|Pifia|Difícil de ver...|Hard to watch...|Difícil de assistir...
can_pifia_02|Pifia|¡Coordina tus ataques!|Coordinate your attacks!|Coordene seus ataques!
";

    private const string ContenidoDuelista = @"
due_inicio_01|ComenzarBatalla|Bueno, equipo: momento de bailar.|All right, team: time to dance.|Muito bem, equipe: hora de dançar.
due_inicio_02|ComenzarBatalla|¿Listos? Yo nací lista.|Ready? I was born ready.|Prontos? Eu nasci pronta.
due_idle_01|IdleTurno|¿Este turno incluye una siesta?|Does this turn include a nap?|Este turno inclui uma soneca?
due_idle_02|IdleTurno|La punta afilada hacia el enemigo. Es fácil...|Pointy end toward the enemy. It's easy...|A ponta afiada fica virada para o inimigo. É fácil...
due_mata_01|EnemigoDerrotado|¡Qué destreza tienes!|Such skill!|Quanta destreza!
due_mata_02|EnemigoDerrotado|Último golpe, sutil...|A subtle finishing blow...|Um golpe final sutil...
due_muere_01|AliadoDerrotado|Oye... todavía no terminamos nuestra charla.|Hey... we weren't done talking yet.|Ei... ainda não terminamos nossa conversa.
due_muere_02|AliadoDerrotado|Malditos sean…|Damn them…|Malditos sejam…
due_refuerzo_01|RefuerzoEnemigo|¡Llegaron tarde!|You're late!|Chegaram tarde!
due_refuerzo_02|RefuerzoEnemigo|Más invitados… más sangre…|More guests… more blood…|Mais convidados… mais sangue…
due_crit_rec_01|CriticoRecibido|¡Ay!|Ow!|Ai!
due_crit_rec_02|CriticoRecibido|Hmpf... Buen golpe.|Hmph... Good hit.|Hmpf... Bom golpe.
due_crit_hecho_01|CriticoRealizado|Directo al orgullo.|Right in the pride.|Bem no orgulho.
due_crit_hecho_02|CriticoRealizado|¡Directo a un órgano!|Right in an organ!|Bem em um órgão!
due_moral_mas_01|MoralAumentaEtapa|¡Lo tenemos, compañeros!|We've got this, friends!|Nós conseguimos, companheiros!
due_moral_mas_02|MoralAumentaEtapa|Eso es... con confianza...|That's it... with confidence...|Isso... com confiança...
due_moral_menos_01|MoralDisminuyeEtapa|Emmm… sin caras largas...|Umm… no long faces...|Humm… nada de caras tristes...
due_moral_menos_02|MoralDisminuyeEtapa|Vamos, todavía no llegó la parte terrible.|Come on, we haven't reached the terrible part yet.|Vamos, a parte terrível ainda nem chegou.
due_apoyo_01|HabilidadAliadaRecibida|Sabía que era tu favorita.|I knew I was your favorite.|Eu sabia que era sua favorita.
due_apoyo_02|HabilidadAliadaRecibida|Buen trabajo. Te debo una…|Nice work. I owe you one…|Bom trabalho. Fico te devendo uma…
due_vida_critica_01|VidaCritica|Eso estuvo demasiado cerca...|That was far too close...|Essa passou perto demais...
due_vida_critica_02|VidaCritica|Aún me queda una estocada.|I still have one thrust left.|Ainda me resta uma estocada.
due_pifia_01|Pifia|¡Magnífico! Ahora con la parte afilada...|Magnificent! Now try the sharp end...|Magnífico! Agora tente com a parte afiada...
due_pifia_02|Pifia|Al menos lo intentas…|At least you're trying…|Pelo menos você está tentando…
";
}
